// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgeetcuboxcmfdgimoat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnZWV0Y3Vib3hjbWZkZ2ltb2F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDE4MzIsImV4cCI6MjA2NjI3NzgzMn0._qw-Xc0VdVvw6Dg-s-3-hqSB1vds64qJ4Ttmfw4nRr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);